language: c
os:
    - linux
addons:
    apt:
        packages:
            - autoconf
            - autoconf2.13
            - autoconf2.64
            - automake
            - clang
            - libtool
            - m4
            - texinfo
            - libgmp-dev
            - libmpfr-dev
            - libmpc-dev
            - yasm
script:
    - (cd js/src; autoconf2.13)
    - mkdir mybuild
    - (cd mybuild; ../js/src/configure --disable-debug --disable-tests --without-system-zlib; make)
